// Generated by https://quicktype.io

export interface ResponseUser {
  userDto: UserDto;
  loginResponseDto: LoginResponseDto;
}

export interface LoginResponseDto {
  jwtToken: string;
}

export interface UserDto {
  nombres: string;
  correo: string;
  contrasenna: null;
}
